# Build stage
FROM maven:3.8.7-openjdk-18 AS build
WORKDIR /build
COPY epic-games-hub/pom.xml .
RUN mvn dependency:go-offline
COPY epic-games-hub/src ./src
RUN mvn clean package -DskipTests

# Runtime stage
FROM amazoncorretto:17
ARG PROFILE=dev
ARG APP_VERSION=1.0.1-SNAPSHOT

WORKDIR /app
COPY --from=build /build/target/epic-games-hub-${APP_VERSION}.jar /app/

EXPOSE 8088

ENV DB_URL=jdbc:postgresql://postgres-sql-bsn:5432/epic_games_hub
ENV MAILDEV_URL=localhost

ENV ACTIVE_PROFILE=${PROFILE}
ENV JAR_VERSION=${APP_VERSION}
ENV EMAIL_HOST_NAME: missing_host_name
ENV EMAIL_USER_NAME: missing_user_name
ENV EMAIL_PASSWORD: missing_password

CMD java -jar -Dspring.profiles.active=${ACTIVE_PROFILE} -Dspring.datasource.url=${DB_URL} epic-games-hub-${JAR_VERSION}.jar
