version: "3.8"

services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: epic_games_hub
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.1-SNAPSHOT
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
    environment:
      - DB_URL=jdbc:postgresql://postgres-sql-bsn:5432/epic_games_hub
      - ACTIVE_PROFILE=dev
      - JAR_VERSION=1.0.1-SNAPSHOT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://postgres:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0-SNAPSHOT
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
