FROM node:18 as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:alpine

COPY epic-games-hub-ui/nginx.conf /etc/nginx/nginx.conf

COPY --from=build-stage /app/dist/epic-games-hub-ui /usr/share/nginx/html

EXPOSE 80
